DESIGN_NAME: spm
VERILOG_FILES: dir::src/*.v

# --- CLOCK & TIMING ---
CLOCK_PORT: clk
CLOCK_PERIOD: 10.0
IO_DELAY_CONSTRAINT: 20
PNR_SDC_FILE: dir::src/impl.sdc
SIGNOFF_SDC_FILE: dir::src/signoff.sdc

# --- SYNTHESIS ---
SYNTH_STRATEGY: "DELAY 0"
SYNTH_ABC_BUFFERING: true
SYNTH_SIZING: true
MAX_FANOUT_CONSTRAINT: 8

# --- FLOORPLANNING  ---
FP_SIZING: "relative"
FP_CORE_UTIL: 45

# --- PDN CONFIGURATION  ---
FP_PDN_CORE_RING: true
FP_PDN_ENABLE_RAILS: true
FP_PDN_VOFFSET: 10
FP_PDN_HOFFSET: 10
FP_PDN_VWIDTH: 2
FP_PDN_HWIDTH: 2
FP_PDN_VPITCH: 30
FP_PDN_HPITCH: 30
FP_PDN_SKIPTRIM: true

# --- CTS CONFIGURATION ---
CTS_ROOT_BUFFER: sky130_fd_sc_hd__clkbuf_8
CTS_CLK_BUFFERS:
  - sky130_fd_sc_hd__clkbuf_2
  - sky130_fd_sc_hd__clkbuf_4
  - sky130_fd_sc_hd__clkbuf_8

# --- PLACEMENT & ROUTING ---
PL_TARGET_DENSITY_PCT: 45
PL_TIMING_DRIVEN: true
PL_ROUTABILITY_DRIVEN: true
GPL_CELL_PADDING: 1
DPL_CELL_PADDING: 1

# --- IO PIN CONFIGURATION ---
IO_PIN_ORDER_CFG: dir::pin_order.cfg

# --- PDK OVERRIDES ---
pdk::sky130*:
  FP_CORE_UTIL: 45
  MAX_FANOUT_CONSTRAINT: 8
  MAX_TRANSITION_CONSTRAINT: 0.75
  scl::sky130_fd_sc_hd:
    CLOCK_PERIOD: 10.0
